# 应用端口
server:
  port: 7901
spring:
  application:
    # 应用名称
    name: provider-user

# eureka 配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://yinliqing:1234567@localhost:8761/eureka
# 开启负载均衡
ribbon:
  eureka:
    enabled: true
    
logging:
  level:
    root: INFO
