server:
  port: 8001
spring:
  application:
    name: microservice-consumer

# eureka 配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://yinliqing:1234567@localhost:8761/eureka
logging:
  level:
    root: INFO
