server:
  port: 9000
spring:
  application:
    name: gateway-zuul
eureka:
  client:
    registry-with-eureka: false 
    fetch-registry: false
    serviceUrl:
      # defaultZone: http://localhost:8761/eureka
      defaultZone: http://yinliqing:1234567@localhost:8761/eureka
zuul:
  ribbonIsolationStrategy: THREAD
  host:
    connect-timeout-millis: 6000
    socket-timeout-millis: 6000
  ignoredServices: '*'
  routes:
    app-a:
      path: /u/**
      url: http://localhost:7901/
    app-b:
      path: /c/**
      serviceId: provider-user

hystrix:
  command:
    provider-user:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 7000

provider-user:
  ribbon:
    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
    listOfServers: localhost:7901,localhost:7902
    ConnectTimeout: 1000
    ReadTimeout: 3000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100

# 开启负载均衡
# ribbon.eureka.enable=true
ribbon:
  eureka:
    enabled: true
    
# feign.hystrix.enabled=true
feign:
  hystrix:
    enabled: true


